### ISSUE TITLE
HOL3 Missing permissions config

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#65] opened 2016-11-21 02:01 UTC
There is a missing permissions config for HOL 3
See screenshot

![hol 3 missing permissionsconfig](https://cloud.githubusercontent.com/assets/15032819/20468402/00c3d730-afc9-11e6-94bc-7b7b6579658b.png)

**Comment by ivegamsft** [comment] 2016-11-22 02:48
Duplicate of #44

**Closed by ivegamsft** 2016-11-22 02:48 UTC
